name: daily-runs

on: [push]
# on:
#   schedule:
#     - cron: '0 0 * * *'

jobs:
  ci:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8.13']
        poetry-version: ['1.2.2']
      runs-on: {{ maxtrix.os }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} # install the python version needed

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: {{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install library
        run: poetry install --no-interaction

      - name: execute py script # run main.py
        run: python ozbargain-bot.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
